version: '3.4'

services:
  srmqia:
    image: ${DOCKER_REGISTRY}srmqia
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      - "Host=RMQ"
  RMQ:
    image: rabbitmq:3-management
    ports:
      - "8081:15672"
